<a href="https://colab.research.google.com/github/sv650s/amazon-review-classification/blob/master/notebooks/deep_learning/6.5.6-LSTMB16-GloVe-problematic-categories-all-ratings-1m.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook, we will look at review samples from mis-classified examples

We are loading pre-trained model with 1mil example dataset

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import sys
DRIVE_DIR = "drive/My Drive/Springboard/capstone"
sys.path.append(DRIVE_DIR)


%tensorflow_version 2.x


import tensorflow as tf
# checl to make sure we are using GPU here
tf.test.gpu_device_name()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
TensorFlow 2.x selected.


'/device:GPU:0'

In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals


from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.models import load_model
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Embedding, \
    SpatialDropout1D, Flatten, LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.utils import model_to_dot
from tensorflow.keras.initializers import Constant


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.utils.class_weight import compute_class_weight


import pandas as pd
import numpy as np
from IPython.display import SVG
import pickle
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
import os
import logging


import util.dict_util as du
import util.plot_util as pu
import util.file_util as fu
import util.keras_util as ku
import util.report_util as ru

import random

# fix random seeds
tf.compat.v1.reset_default_graph()
tf.compat.v1.set_random_seed(1)
random.seed(1)
np.random.seed(1)

logging.basicConfig(level=logging.ERROR)

%matplotlib inline
sns.set()


DATE_FORMAT = '%Y-%m-%d'
TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
LABEL_COLUMN = "star_rating"
REVIEW_COLUMN = "review_body"


DEBUG = False


LSTM_DIM = 16 # total LSTM units
MODEL_NAME = f"LSTMB{LSTM_DIM}"
ARCHITECTURE = f"1x{LSTM_DIM}"
DESCRIPTION = f"1 Layer {LSTM_DIM} LSTM Units, No Dropout, GloVe Embedding, Balanced Weights"
FEATURE_SET_NAME = "glove"
PATIENCE = 4

SAMPLES = "1m"

if DEBUG:
  DATA_FILE = f'{DRIVE_DIR}/data/amazon_reviews_us_Wireless_v1_00-test-preprocessed.csv'
  MODEL_NAME = f'test-{MODEL_NAME}'
  MISSING_WORDS_FILE = f'{DRIVE_DIR}/reports/glove_embedding-missing_words-test.csv'
  ku.ModelWrapper.set_report_filename('test-dl_prototype-report.csv')
else:
  DATA_FILE = f"{DRIVE_DIR}/data/amazon_reviews_us_Wireless_v1_00-{SAMPLES}-preprocessed.csv"
  MISSING_WORDS_FILE = f'{DRIVE_DIR}/reports/glove_embedding-missing_words-{SAMPLES}.csv'
  ku.ModelWrapper.set_report_filename('glove_embedding-dl_prototype-report.csv')


EMBEDDING_FILE = f'{DRIVE_DIR}/data/embeddings/glove.840B.300d.txt'

# first layer filter
FILTER1 = 32
# Network Settings
KERNEL_SIZE=3



# length of our embedding - 300 is standard
EMBED_SIZE = 300
EPOCHS  = 50
BATCH_SIZE = 128

# From EDA, we know that 90% of review bodies have 100 words or less, 
# we will use this as our sequence length
MAX_SEQUENCE_LENGTH = 100


pd.set_option("max_colwidth", 200)

In [3]:
# Load Report file
report = pd.read_csv(f'{DRIVE_DIR}/reports/glove_embedding-dl_prototype-report.csv', quotechar="'")
report = report[(report.model_name == 'LSTMB16') & (report.train_examples == 746766)]
report

accuracy  ...                                                                                             network_history_file
11  0.707173  ...  drive/My Drive/Springboard/capstone/reports/LSTMB16-1x16-glove-sampling_none-995688-100-star_rating-history.pkl

[1 rows x 30 columns]

In [4]:
DATA_FILE = report.file.values[0]
print(f'Reading datafile: {DATA_FILE}')
df = pd.read_csv(DATA_FILE, encoding='utf8', engine='python')

rating = df[LABEL_COLUMN]
reviews = df[REVIEW_COLUMN]

Reading datafile: drive/My Drive/Springboard/capstone/data/amazon_reviews_us_Wireless_v1_00-1m-preprocessed.csv


# Preprocessing

In [5]:


# pre-process our lables
# one hot encode our star ratings since Keras/TF requires this for the labels
ohe = OneHotEncoder()
y = ohe.fit_transform(rating.values.reshape(len(rating), 1)).toarray()


# split our data into train and test sets
reviews_train, reviews_test, y_train, y_test = train_test_split(reviews, y, random_state=1)

with open(report.tokenizer_file.values[0], 'rb') as file:
  t = pickle.load(file)

# Pre-process our features (review body)
# t = Tokenizer(oov_token="<UNK>")
# fit the tokenizer on the documents
# t.fit_on_texts(reviews_train)
# tokenize both our training and test data
train_sequences = t.texts_to_sequences(reviews_train)
test_sequences = t.texts_to_sequences(reviews_test)

print("Vocabulary size={}".format(len(t.word_counts)))
print("Number of Documents={}".format(t.document_count))


# pad our reviews to the max sequence length
X_train = sequence.pad_sequences(train_sequences, maxlen=MAX_SEQUENCE_LENGTH)
X_test = sequence.pad_sequences(test_sequences, maxlen=MAX_SEQUENCE_LENGTH)

print('Train review vectors shape:', X_train.shape, ' Test review vectors shape:', X_test.shape)


Vocabulary size=109547
Number of Documents=746766
Train review vectors shape: (746766, 100)  Test review vectors shape: (248922, 100)


# Load Our Pre-trained Model

In [0]:
from tensorflow.keras.models import load_model

model = load_model(report.model_file.values[0])

Double checking our accuracy. It should be: 70.60%

In [7]:
scores = model.evaluate(X_test, y_test, verbose=1)


248922/248922 [==============================] - 114s 458us/sample - loss: 0.7492 - categorical_accuracy: 0.7072


In [8]:
print("Loss: %.2f%%" % (scores[0]*100))
print("Accuracy: %.2f%%" % (scores[1]*100))


Loss: 74.92%
Accuracy: 70.72%


In [9]:
# look at a couple prediction results
y_predict = model.predict(X_test)
y_predict[:5]

array([[6.6044432e-04, 1.2262755e-03, 1.0042071e-02, 1.4336163e-01,
        8.4470958e-01],
       [4.8195251e-04, 7.5134105e-04, 8.3812112e-03, 1.2789713e-01,
        8.6248833e-01],
       [3.7696629e-04, 1.3154644e-03, 1.9974884e-02, 1.9462089e-01,
        7.8371179e-01],
       [2.0780079e-03, 3.1067615e-03, 1.8840974e-02, 1.2706077e-01,
        8.4891349e-01],
       [9.5476207e-05, 1.0342833e-04, 1.2387980e-03, 5.4122183e-02,
        9.4444013e-01]], dtype=float32)

# Unencode our labels back to 1 to 5 so we can look at confusion matrix and classification report

In [0]:
y_test_unencoded = ku.unencode(y_test)
y_predict_unencoded = ku.unencode(y_predict)

In [11]:
from sklearn.metrics import confusion_matrix, classification_report

cr = classification_report(y_test_unencoded, y_predict_unencoded)
print(cr)

              precision    recall  f1-score   support

           1       0.66      0.84      0.74     35163
           2       0.38      0.12      0.18     16498
           3       0.41      0.34      0.38     22359
           4       0.51      0.30      0.38     41315
           5       0.79      0.93      0.86    133587

    accuracy                           0.71    248922
   macro avg       0.55      0.51      0.51    248922
weighted avg       0.67      0.71      0.67    248922



In [12]:
confusion_matrix = confusion_matrix(y_test_unencoded, y_predict_unencoded)
print(confusion_matrix)

[[ 29525   1480   1969    398   1791]
 [  8086   1991   3933    837   1651]
 [  4024   1369   7685   4346   4935]
 [  1236    248   3622  12214  23995]
 [  1534    123   1389   5925 124616]]


In [13]:
classification_report = classification_report(y_test_unencoded, y_predict_unencoded)
print(classification_report)

              precision    recall  f1-score   support

           1       0.66      0.84      0.74     35163
           2       0.38      0.12      0.18     16498
           3       0.41      0.34      0.38     22359
           4       0.51      0.30      0.38     41315
           5       0.79      0.93      0.86    133587

    accuracy                           0.71    248922
   macro avg       0.55      0.51      0.51    248922
weighted avg       0.67      0.71      0.67    248922



In [14]:
result = pd.DataFrame({"test": y_test_unencoded, "predict": y_predict_unencoded})
result.head()

test  predict
0     5        5
1     5        5
2     5        5
3     5        5
4     5        5

In [15]:
# add column to tell use which ones are misclassified
result["correct"] = result.test == result.predict

print(result[result.correct == True].sample(5))

result[result.correct == False].sample(5)

        test  predict  correct
190112     5        5     True
127893     5        5     True
94518      5        5     True
240572     5        5     True
40951      5        5     True


test  predict  correct
246527     2        3    False
150148     2        1    False
33492      3        2    False
179340     4        5    False
107012     5        4    False

# Load our embedding indexer to see what words may have been removed

In [16]:
EMBEDDING_INDEX_FILE = f'{DRIVE_DIR}/models/glove.840B.300d-embedding_index'

embeddings_index = {}

if os.path.exists(f'{EMBEDDING_INDEX_FILE}.npy'):
  print(f'Loading {EMBEDDING_INDEX_FILE}.npy')
  embeddings_index = np.load(f'{EMBEDDING_INDEX_FILE}.npy', 
                             allow_pickle = True).item()
else:
  print('Indexing word vectors.')

  with open(EMBEDDING_FILE) as f:
      for line in f:
          word, coefs = line.split(maxsplit=1)
          coefs = np.fromstring(coefs, 'f', sep=' ')
          embeddings_index[word] = coefs
  np.save(EMBEDDING_INDEX_FILE, embeddings_index)

print(type(embeddings_index))
print(np.shape(embeddings_index))
print('Found %s word vectors.' % len(embeddings_index))

Loading drive/My Drive/Springboard/capstone/models/glove.840B.300d-embedding_index.npy
<class 'dict'>
()
Found 2195884 word vectors.


# reset reviews index so it matches our result dataframe


In [0]:
reviews_reset = reviews_test.reset_index().rename({"index": "index_orig"}, axis=1)

# Incorrectly classified 1-star reviews

In [18]:
incorrect_result = result[(result.test == 1) & (result.correct == False)]
incorrect_idx = incorrect_result.index.tolist()
incorrect_pd = pd.merge(incorrect_result, reviews_reset.loc[incorrect_idx], left_index = True, right_index = True).sample(min(20, len(incorrect_result)), random_state=1)
incorrect_pd["out_of_vocab"] = ""

for index, row in incorrect_pd.iterrows():
  review_body = row.review_body
  missing_words = [word for word in review_body.split() if word not in embeddings_index.keys()]
  incorrect_pd.loc[index, "out_of_vocab"] = ", ".join(missing_words)

incorrect_pd

test  ...  out_of_vocab
78152      1  ...              
84008      1  ...              
41477      1  ...              
90324      1  ...              
41459      1  ...              
75727      1  ...              
142551     1  ...              
152371     1  ...      slotcons
206812     1  ...              
17015      1  ...              
65739      1  ...     arrrrgggg
87243      1  ...    ampossible
109483     1  ...          ampy
238111     1  ...              
220203     1  ...              
10568      1  ...              
89575      1  ...              
127451     1  ...              
196871     1  ...   ammediately
177647     1  ...              

[20 rows x 6 columns]

# Incorrectly classified 2-star ratings

In [19]:
incorrect_result = result[(result.test == 2) & (result.correct == False)]


incorrect_idx = incorrect_result.index.tolist()
incorrect_pd = pd.merge(incorrect_result, reviews_reset.loc[incorrect_idx], left_index = True, right_index = True).sample(min(20, len(incorrect_result)), random_state=1)
incorrect_pd["out_of_vocab"] = ""

for index, row in incorrect_pd.iterrows():
  review_body = row.review_body
  missing_words = [word for word in review_body.split() if word not in embeddings_index.keys()]
  incorrect_pd.loc[index, "out_of_vocab"] = ", ".join(missing_words)

incorrect_pd

test  ...          out_of_vocab
197981     2  ...                      
79866      2  ...                      
214594     2  ...                      
45690      2  ...                      
182039     2  ...                      
34548      2  ...                      
194589     2  ...               amarily
58808      2  ...                      
28147      2  ...                      
210006     2  ...                      
123472     2  ...  ampractical, phoneso
47526      2  ...                      
138412     2  ...                      
195823     2  ...                      
83640      2  ...                      
139607     2  ...                      
78880      2  ...                      
128341     2  ...                      
72995      2  ...                      
158372     2  ...                spigen

[20 rows x 6 columns]

# Incorrectly classified 3-star ratings

In [20]:
incorrect_result = result[(result.test == 3) & (result.correct == False)]

incorrect_idx = incorrect_result.index.tolist()
incorrect_pd = pd.merge(incorrect_result, reviews_reset.loc[incorrect_idx], left_index = True, right_index = True).sample(min(20, len(incorrect_result)), random_state=1)
incorrect_pd["out_of_vocab"] = ""

for index, row in incorrect_pd.iterrows():
  review_body = row.review_body
  missing_words = [word for word in review_body.split() if word not in embeddings_index.keys()]
  incorrect_pd.loc[index, "out_of_vocab"] = ", ".join(missing_words)

incorrect_pd

test  ...  out_of_vocab
16952      3  ...              
57253      3  ...        prioed
193140     3  ...              
40630      3  ...              
88139      3  ...              
183607     3  ...              
213024     3  ...              
247535     3  ...          amsy
21895      3  ...              
99130      3  ...              
162990     3  ...              
244155     3  ...              
89837      3  ...              
35441      3  ...     amportant
48791      3  ...              
157972     3  ...              
244174     3  ...              
203085     3  ...       picthey
143735     3  ...              
111253     3  ...              

[20 rows x 6 columns]

# 5-star misclassifed as 1-star

In [21]:
incorrect_result = result[(result.test == 5) & (result.predict == 1) & (result.correct == False)]

incorrect_idx = incorrect_result.index.tolist()
incorrect_pd = pd.merge(incorrect_result, reviews_reset.loc[incorrect_idx], left_index = True, right_index = True).sample(min(20, len(incorrect_result)), random_state=1)
incorrect_pd["out_of_vocab"] = ""

for index, row in incorrect_pd.iterrows():
  review_body = row.review_body
  missing_words = [word for word in review_body.split() if word not in embeddings_index.keys()]
  incorrect_pd.loc[index, "out_of_vocab"] = ", ".join(missing_words)

incorrect_pd


test  ...            out_of_vocab
11683      5  ...                        
168067     5  ...                        
43488      5  ...                        
20315      5  ...                        
115825     5  ...                        
220582     5  ...                        
111308     5  ...  beautifuleasy, offvery
154294     5  ...                        
28470      5  ...                        
181438     5  ...                        
99600      5  ...                        
190855     5  ...                        
165860     5  ...                 amefuel
233524     5  ...                        
33713      5  ...                        
110870     5  ...                        
160620     5  ...                   kushy
131503     5  ...               amportant
160045     5  ...                        
184199     5  ...                        

[20 rows x 6 columns]

# 1-star misclassified as 5-star


In [22]:
incorrect_result = result[(result.test == 1) & (result.predict == 5) & (result.correct == False)]

incorrect_idx = incorrect_result.index.tolist()
incorrect_pd = pd.merge(incorrect_result, reviews_reset.loc[incorrect_idx], left_index = True, right_index = True).sample(min(20, len(incorrect_result)), random_state=1)
incorrect_pd["out_of_vocab"] = ""

for index, row in incorrect_pd.iterrows():
  review_body = row.review_body
  missing_words = [word for word in review_body.split() if word not in embeddings_index.keys()]
  incorrect_pd.loc[index, "out_of_vocab"] = ", ".join(missing_words)

incorrect_pd

test  ...       out_of_vocab
173577     1  ...               amum
91042      1  ...                   
111674     1  ...             fosmon
106040     1  ...           ambursed
215459     1  ...                   
170903     1  ...                   
27683      1  ...                   
125919     1  ...                   
22857      1  ...                   
80067      1  ...                   
196013     1  ...           acepower
15975      1  ...                   
241473     1  ...                   
15200      1  ...       contrucction
139958     1  ...                   
134914     1  ...                   
193483     1  ...  mobilitysolutions
91707      1  ...                   
247038     1  ...                   
37389      1  ...                   

[20 rows x 6 columns]

# 4-star misclassified as 5-star

In [23]:
incorrect_result = result[(result.test == 4) & (result.predict == 5) & (result.correct == False)]

incorrect_idx = incorrect_result.index.tolist()
incorrect_pd = pd.merge(incorrect_result, reviews_reset.loc[incorrect_idx], left_index = True, right_index = True).sample(min(20, len(incorrect_result)), random_state=1)
incorrect_pd["out_of_vocab"] = ""

for index, row in incorrect_pd.iterrows():
  review_body = row.review_body
  missing_words = [word for word in review_body.split() if word not in embeddings_index.keys()]
  incorrect_pd.loc[index, "out_of_vocab"] = ", ".join(missing_words)

incorrect_pd

test  ...  out_of_vocab
222823     4  ...              
129937     4  ...              
85088      4  ...              
216959     4  ...              
14477      4  ...              
3145       4  ...       suckion
235826     4  ...              
224670     4  ...              
2247       4  ...        itmade
241685     4  ...         amals
200393     4  ...              
23253      4  ...              
42337      4  ...              
114184     4  ...              
22985      4  ...              
47791      4  ...              
88231      4  ...              
112329     4  ...              
60122      4  ...              
227725     4  ...              

[20 rows x 6 columns]

In [24]:
print(datetime.now())

2020-02-15 02:22:06.078683
